name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" --exclude '.git*' --exclude 'venv*' ./ $USER@$HOST:/home/ubuntu/playbook-app
        ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST "sudo systemctl restart playbook_app.service"
        ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST "sudo systemctl restart nginx"
        rm -f private_key.pem
