name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        SERVER: ${{ secrets.SERVER }}
        USERNAME: ${{ secrets.USERNAME }}
        NEW_PRIVATE_KEY: ${{ secrets.NPRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa,ecdsa,ed25519 $SERVER >> ~/.ssh/known_hosts
        echo "$NPRIVATE_KEY" > ~/.ssh/github_keys.pem
        chmod 600 ~/.ssh/github_keys.pem
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add ~/.ssh/github_keys.pem

    - name: Deploy to server
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        SERVER: ${{ secrets.SERVER }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        scp -o StrictHostKeyChecking=no -o HostKeyAlgorithms=rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 -r . $USERNAME@$SERVER:/home/ubuntu/playbook-app
        ssh -o StrictHostKeyChecking=no -o HostKeyAlgorithms=rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 $USERNAME@$SERVER "cd /home/ubuntu/playbook-app && git fetch origin main && git reset --hard origin/main && git clean -f -d -x --exclude=.env --exclude=playbook && git pull origin main --force && pip install -r requirements.txt && yarn install && yarn build && sudo systemctl restart playbook_app.service"
