name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: Deploy to the production server
    runs-on: ubuntu-22.04

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END
          cat ~/.ssh/config
          ls -la ~/.ssh
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SERVER }}

      - name: Pull new code onto the server
        run: ssh production "cd /home/ubuntu/playbook-app && git fetch origin main && git reset --hard origin/main && git clean -f -d -x --exclude=.env && git pull origin main --force"

      - name: Update libraries
        run: ssh production "cd /home/ubuntu/playbook-app && pip install -r requirements.txt && yarn install"

      - name: Rebuild assets
        run: ssh production "cd /home/ubuntu/playbook-app && yarn build"

      - name: Restart services
        run: ssh production "cd /home/ubuntu/playbook-app && sudo systemctl restart playbook_app.service"

      - name: Cleanup
        run: rm -rf ~/.ssh
