name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        SERVER: ${{ secrets.SERVER }}
        USERNAME: ${{ secrets.USERNAME }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        echo "$SSH_PUBLIC_KEY" >> ~/.ssh/known_hosts
        scp -i private_key.pem -o StrictHostKeyChecking=no -r . $USERNAME@$SERVER:/home/ubuntu/playbook-app
        ssh -i private_key.pem -o StrictHostKeyChecking=no $USERNAME@$SERVER "cd /home/ubuntu/playbook-app && git fetch origin main && git reset --hard origin/main && git clean -f -d -x --exclude=.env --exclude=playbook && git pull origin main --force && pip install -r requirements.txt && yarn install && yarn build && sudo systemctl restart playbook_app.service"
        rm -f private_key.pem
